### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by tezano** [KANG-NEWBIE/lk21-dl#1]
di mac os kok error di line 30 ya ?

**Comment by zasuu** [comment]
Ini nyimpen nya keana bang? Nama folder nya apa?

**Comment by fajaraditio** [comment]
iya, ada error di line 30 / 31

**Comment by fachryansyah** [comment]
pake python --version berapa ? upgrade ke python 3.x.x problem solved

**Comment by sinoobie** [comment]
untuk di mac ataupun di linux gunakan "python3 lk21.py" karna biasanya perintah "python" itu untuk python v2

**Comment by sinoobie** [comment]
> Ini nyimpen nya keana bang? Nama folder nya apa?

semua hasil download akan disimpen di folder "result" ya gan...
